// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.NamND.Models;

public partial class SurveyQuestionsNamND
{
    public int QuestionNamNDID { get; set; }

    public int SurveyNamNDID { get; set; }

    public string QuestionText { get; set; }

    public int QuestionOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string QuestionType { get; set; }

    public bool IsRequired { get; set; }

    public string Options { get; set; }

    public int? RiskWeight { get; set; }

    public string HelpText { get; set; }

    public string Section { get; set; }

    public string Tag { get; set; }

    public string Language { get; set; }

    public int? DependsOnQuestionID { get; set; }

    public string DependsOnAnswer { get; set; }

    public int? MinScore { get; set; }

    public int? MaxScore { get; set; }

    public string DisplayStyle { get; set; }

    public string ImageURL { get; set; }

    public virtual SurveysNamND SurveyNamND { get; set; }
}